export const API_ENDPOINTS = {
  LOGIN: '/login',
  REGISTER: '/register',

  HOMEPAGE_BANNER: "/homepage/banners",
  NEW_ARRIVAL_PRODUCTS: "/homepage/new-arrivals",
  RECENTLY_VIEWED: "/homepage/recently-viewed-products",
  FLASH_SALE: "/homepage/flash-sale",
  TOP_CATEGORIES: "/homepage/top-selling-categories",
  OFFER_BANNER: "/homepage/offer-banner",
  PRODUCT: "https://throttle-space-backend-service-app.onrender.com/api/products/product/",
  CATEGORIES: 'https://throttle-space-backend-service-app.onrender.com/api/category/show',

  LOGOUT: '/logout',
  FORGET_PASSWORD: '/forget-password',
  CATEGORIES_2: '/categories.json',
  CATEGORIES_ANCIENT: '/categories_ancient.json',
  FEATURED_CATEGORIES: '/featured_categories.json',
  COLLECTIONS: '/collections.json',
  BRANDS: '/brands.json',
  BRANDS_ANCIENT: '/brands_ancient.json',
  PRODUCTS: '/products.json',
  PRODUCTS_2: '/products_2.json',
  PRODUCTS_ANCIENT: '/products_ancient.json',
  FEATURED_PRODUCTS: '/featured_products.json',
  FEATURED_PRODUCTS_ANCIENT: '/featured_products_ancient.json',
  TOP_SELLER_PRODUCTS: '/products_top_seller.json',
  ON_SELLING_PRODUCTS: '/products_on_selling.json',

  RELATED_PRODUCTS: '/related_products.json',
  BEST_SELLER_PRODUCTS: '/products_best_seller.json',

  POPULAR_PRODUCTS: '/products_popular.json',
  NEW_ARRIVAL_PRODUCTS_ANCIENT: '/products_new_arrival.json',
  FLASH_SALE_PRODUCTS: '/products_flash_sale.json',
  FLASH_SALE_PRODUCTS_ANCIENT: '/products_flash_sale_ancient.json',
  SHOPS: '/shops.json',
  SHOP: '/shop.json',
  SEARCH: '/search.json',
  ORDERS: '/orders.json',
  ORDER: '/order.json',
};
